name: documentmanager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0 # Update firebase_core to the latest v3.x.x
  firebase_auth: ^5.5.3 # Update firebase_auth to the latest v5.x.x
  cloud_firestore: ^5.6.7 # Update cloud_firestore to the latest v5.x.x
  firebase_storage: ^12.4.5 # Keep firebase_storage at the latest v12.x.x
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
